config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable # confirmableを追加
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /blogs
  # GET /blogs.json
  def index
#    raise
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
#    raise
  end

  # GET /blogs/new
  def new
#    raise
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
#    raise
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
       # raise
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
#    raise
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    #raise
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="ja" > 
<meta charset="UTF-8"> 
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">

<head>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width">
  <title>麹町ハッカー部</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<div class="boxA">
  <div class="box1">
    <div class="site">
      <h1><a href="#">麹町ハッカー部 by 野呂浩良</a></h1>
    </div>
  </div>

  <div class="box2">
    <nav class="menu">
      <ul>
        <li><a href="#">トップ</a></li>
        <li><a href="#">お問い合わせ</a></li>
        <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

<div class="box3">
  <%= image_tag("header.png", class: "topimg", class: "img-responsive") %>
</div>

<div class="box4">
  <div class="box4-1">
    <div class="merit">
      <a href="#">
      <i class="fa fa-database"></i>        
      <h1>GMBA生向け</h1>
        <p>Globis Entrepreners Club Member 限定の特別プログラム。DAY1受講から6ヶ月でMBAハッカーに進化させます。</p>
      </a>
    </div>
  </div>
  <div class="box4-2">
    <div class="merit">
      <a href="#">
      <i class="fa fa-bar-chart"></i>
        <h1>オンラインサポート付き</h1>
        <p>専用のfacebookグループ内やNitrousのコラボレーション機能を経由して随時オンラインサポート
          </p>
      </a>
    </div>
  </div>
  <div class="box4-3">
    <div class="merit">
      <a href="#">
      <i class="fa fa-envelope"></i>
      <h1>チーム開発＆ハッカソン</h1>
        <p>MBA生によるビジネスアイデアに基づいてリーンスタートアップとチーム開発を開催・実践します
      </p>
      </a>
    </div>
  </div></div>

<div class="box5">
  <div class="copyright">
    <p>Copyright &copy; Dive into Code feat.麹町ハッカー部</p>
  </div>
</div>